name: React CI

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-ci
      - run: npm test